FROM node:24-alpine

WORKDIR /app

RUN npm install -g bun@latest

COPY ./web/package.json .
COPY ./web/bun.lock .

RUN bun install --frozen-lockfile

COPY ./web .

EXPOSE 3000

CMD ["bun", "run", "dev"]
