services:
  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis
    ports:
      - "6379:6379"

  migrate:
    image: migrate/migrate
    volumes:
      - ./common/db/migrations/:/migrations
    command:
      [ "-path", "/migrations", "-database", "postgres://postgres:secret@db:5432/postgres?sslmode=disable", "up" ]
    depends_on:
     db:
      condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./infra/Docker/api/Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - .env:/app/api/.env
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app/api
          ignore:
            - bin
            - tmp
        - action: sync
          path : ./common
          target: /app/common
  
  publisher:
    build:
      context: .
      dockerfile: ./infra/Docker/publisher/Dockerfile
    volumes:
      - .env:/app/.env
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  worker:
    build:
      context: .
      dockerfile: ./infra/Docker/worker/Dockerfile
    volumes:
      - .env:/app/.env
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully


  db-worker:
    build:
      context: .
      dockerfile: ./infra/Docker/db-worker/Dockerfile
    volumes:
      - .env:/app/.env
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: ./infra/Docker/web/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web/.env:/app/.env
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
