// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Websitestatus string

const (
	WebsitestatusUp      Websitestatus = "Up"
	WebsitestatusDown    Websitestatus = "Down"
	WebsitestatusUnknown Websitestatus = "Unknown"
)

func (e *Websitestatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Websitestatus(s)
	case string:
		*e = Websitestatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Websitestatus: %T", src)
	}
	return nil
}

type NullWebsitestatus struct {
	Websitestatus Websitestatus
	Valid         bool // Valid is true if Websitestatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebsitestatus) Scan(value interface{}) error {
	if value == nil {
		ns.Websitestatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Websitestatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebsitestatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Websitestatus), nil
}

type Region struct {
	ID   uuid.UUID
	Name string
}

type Website struct {
	ID        uuid.UUID
	Url       string
	CreatedAt time.Time
}

type Websitetick struct {
	ID             uuid.UUID
	ResponseTimeMs int32
	Status         Websitestatus
	RegionId       uuid.UUID
	WebsiteId      uuid.UUID
}
