// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: website.sql

package db

import (
	"context"
	"time"
)

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO website (url, "createdAt")
VALUES ($1, $2)
RETURNING id, url, "createdAt"
`

type CreateWebsiteParams struct {
	Url       string
	CreatedAt time.Time
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRowContext(ctx, createWebsite, arg.Url, arg.CreatedAt)
	var i Website
	err := row.Scan(&i.ID, &i.Url, &i.CreatedAt)
	return i, err
}

const listWebsites = `-- name: ListWebsites :many
SELECT id, url, "createdAt" FROM website
`

func (q *Queries) ListWebsites(ctx context.Context) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Website
	for rows.Next() {
		var i Website
		if err := rows.Scan(&i.ID, &i.Url, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
